spring.application.name=sistema-biblioteca

spring.data.mongodb.uri=mongodb+srv://munirabouzenni_db_user:moonstruck99@biblioteca.enmxsi0.mongodb.net/?appName=Biblioteca
spring.data.mongodb.database=biblioteca

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Server
server.port=8080
